export default () => {
    return 123;
};

// RULES OF REDUCERS:
// J MUST RETURN ANY VALUE BESIDES UNDEFINED
// J WHEN REDUX FIRST BOOTS UP IT RUNS REDUCERS ONE TIME
// J PRODUCES STATE OR DATA TO BE USED INSIDE OF YOUR APP USING ONLY PREVIOUS STATE AND THE ACTION
// J  (undefined)(ACTION) >> (Reducer) >> State
// J 